### ISSUE TITLE
Youtube channels are broken

### ISSUE THREAD

**Issue by LivingWithHippos** [pluja/Parasitter#195] opened 2021-03-04 14:49 UTC
**Describe the bug**
Opening a youtube channel returns an 500 error page with Yotter

**To Reproduce**
1. Do a search or open your Yotter Youtube feed
2. Press on a channel link
3. An error page is shown

**Expected behavior**
The channel page with all the available videos open. It worked fine until a couple of weeks ago I think.

**Desktop (please complete the following information):**
 - OS: manjaro linux
 - Browser: firefox
 - Version: any

**Additional context**

It is my own self hosted instance. The relevant docker log is this:

```python
ERROR in app: Exception on /c/UCr6Ojg6WA9Lk-ynphZE9gtg [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/usr/src/app/app/routes.py", line 432, in channel
    data = ytch.get_channel_tab_info(id, page, sort)
  File "/usr/src/app/youtube/channel.py", line 123, in get_channel_tab_info
    content = util.fetch_url(url,
  File "/usr/src/app/youtube/util.py", line 178, in fetch_url
    raise FetchError(str(response.status), reason=response.reason, ip=None)
youtube.util.FetchError: HTTP error during request: 404 Not Found
```
THe browser shows a `500 Internal Server Error` network call. I can watch videos normally.

**Comment by pluja** [comment] 2021-03-05 10:16
Thank you, I will try to dig into this this weekend!

**Comment by user234683** [comment] 2021-03-06 08:18
Fixed in these two commits:
- [Use new channel api endpoint now that browse_ajax is disabled ](https://github.com/user234683/youtube-local/commit/b9682f26e26e0c74b802d2c6cbe89c992c4d823a)
- [Fix channel search ](https://github.com/user234683/youtube-local/commit/e92c5fe2684cbb0dbe16470a081c79b6b6e7d603)

The second one is applying the same fix to the channel search since I forgot to test that in the first one. Prerequisite bug fix for util.fetch_url to fix post requests:
- [util.py: Fix data not being passed in requests ](https://github.com/user234683/youtube-local/commit/fe05aed07cb7d32469a8ff38b3b3af3502df51e0).

Also recommended:
- [util.py: Encode data using utf-8, not ascii ](https://github.com/user234683/youtube-local/commit/a3535d69550e972dc790db96b7d3a583699cb199)

I also did these two commits so the first page for channel videos will use the generic first-page request type, which is less likely to change, so if they keep changing the APIs at least the first page of channels won't break. Not strictly necessary but increases resilience:
- [Channel: use general pbj=1 endpoint to get first page of videos ](https://github.com/user234683/youtube-local/commit/2f6047d06fbfc118cd262832b33e585b6809abf8)
- [Fix regression: Channels not sorting by oldest/popular](https://github.com/user234683/youtube-local/commit/3c2a204cc57d2a7bef357403b3c5be50f474804b)

Second one is a fix to an issue caused by the first one. I didn't test thoroughly so I missed stuff sometimes.

Relevant [invidious issue](https://github.com/iv-org/invidious/issues/1838)

**Closed as completed** 2021-03-12 18:50 UTC
Labels: bug

**Comment by pluja** [comment] 2021-03-12 18:53
This should be fixed now! Thanks to @user234683!
