### ISSUE TITLE
Error: Error decrypting url signatures: Could not find var_body

### ISSUE THREAD

**Issue by arankaren** [pluja/Parasitter#193] opened 2021-02-23 03:28 UTC

**Comment by pluja** [comment] 2021-02-23 08:53
Could you give a bit more context on this error?

**Comment by FireMasterK** [comment] 2021-02-23 09:11
This is an error caused by cipher-protected URLs in YouTube, likely caused by an outdated youtube-dl version, it can be fixed by updating it.

Looks like `yt-dlc` is now no longer maintained.

**Comment by pluja** [comment] 2021-02-23 13:07
Should we go back to `youtube-dl`?

**Comment by FireMasterK** [comment] 2021-02-23 13:34
Yep, seems like the only good option for now.

**Comment by pluja** [comment] 2021-02-23 14:08
Ok. Can you remind me why whe switched to `yt-dlc`? I can't remember why was it

**Comment by FireMasterK** [comment] 2021-02-23 15:28
I believe it was because of faster updates because it was a community-maintained repository.

The maintainers of `youtube-dl` are slow and take forever to fix any breaking changes, they take a long time to review PRs, and didn't want to give more people write access.

You could see more about it at https://github.com/ytdl-org/youtube-dl/issues/26462

**Comment by pluja** [comment] 2021-02-23 17:38
Okay! Thank you. I will check it and change it back to ytdl.

**Comment by pluja** [comment] 2021-02-25 18:13
@FireMasterK I just found this: https://github.com/yt-dlp/yt-dlp

**Comment by FireMasterK** [comment] 2021-02-25 19:30
I heard about it on the Invidious room too, it seems like a good idea to me

**Comment by user234683** [comment] 2021-03-03 04:55
This was fixed [in this commit](https://github.com/user234683/youtube-local/commit/d998fea9b970406b50ee22b1998a52a96bbd1a29). They changed the base.js a little bit. You should be able to take the diff and apply it to watch_extraction.py.

**Comment by pluja** [comment] 2021-03-14 08:36
Closing this as it should be solved. If anyone experiments this error again, we will reopen.

**Closed as completed by pluja** 2021-03-14 08:36 UTC
Labels: bug
