### ISSUE TITLE
Please add dark mode and 1080p quality 

### ISSUE THREAD

**Issue by RouterCFW** [pluja/Parasitter#191] opened 2021-02-14 14:05 UTC
Hello yotter devs is dark mode in the future development ? and could you please add 1080p 60fps quality on videos I believe on invidious it’s called dash quality

**Comment by FireMasterK** [comment] 2021-02-14 15:34
Closing as this is a duplicate of #48.

**Closed as completed by FireMasterK** 2021-02-14 15:34 UTC
Labels: feature request

**Comment by RouterCFW** [comment] 2021-02-14 16:16
Oh I didn’t see it sorry
